### ISSUE TITLE
Original Paper 

### ISSUE THREAD

**Issue by qiunlp** [mickeystroller/R-BERT#3]
你的模型最后结果是 90.16,
Original Paper  结果89.25,   这里的Original Paper 是什么？
89.25是怎么来的？
谢谢！

**Comment by mickeysjm** [comment]
The original paper is https://arxiv.org/pdf/1905.08284.pdf

I directly copy the result from the original paper, which gives us 89.25. 

Thanks.

**Comment by tyistyler** [comment]
EXcuse me, original paper mentioned is "For the pre-trained BERT model, we use the uncased basic model"
